allowBuilds:
  "@parcel/watcher": false
  core-js: true
  esbuild: true
  sharp: true
minimumReleaseAge: 1080 # 18 hours
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 64800 # 18 hours
