name: Dependency Diff

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-diff:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: e18e/action-dependency-diff@9a7f09f5f2993256322e0db17ee4c8d9339dab77 # v1.7.1
        with:
          # Too noisy. Will enable if it ever supports reporting *changes* in duplicates.
          duplicate-threshold: "999"
          # Always report size diff.
          size-threshold: "-1"
