name: Knip

on: [push, pull_request]

jobs:
  knip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Set up PNPM
        run: corepack enable

      - name: Install dependencies
        run: "pnpm install"

      - run: "pnpm run knip"
